"""Protocol constants for LumenTP/1.1."""

VERSION = "LumenTP/1.1"
CRLF = b"\r\n"
HEADER_TERMINATOR = b"\r\n\r\n"
DEFAULT_TIMEOUT_SECONDS = 5.0
MAX_HEADER_BYTES = 64 * 1024
READ_CHUNK_SIZE = 4096
BODY_METHODS = {"SUBMIT", "REPLACE"}
ALLOWED_METHODS = {"FETCH", "SUBMIT", "REPLACE", "REMOVE", "PING"}
DEFAULT_BINARY_TYPE = "application/octet-stream"
DEFAULT_TEXT_TYPE = "text/plain; charset=utf-8"
PROBLEM_JSON_TYPE = "application/problem+json"
AUTH_SCHEME = "Token"
STATUS_REASONS = {
    200: "OK",
    201: "CREATED",
    204: "NO CONTENT",
    400: "BAD REQUEST",
    401: "UNAUTHORIZED",
    404: "NOT FOUND",
    405: "METHOD NOT ALLOWED",
    406: "NOT ACCEPTABLE",
    411: "LENGTH REQUIRED",
    500: "INTERNAL SERVER ERROR",
}
