"""Protocol constants for LumenTP/1.4."""

VERSION = "LumenTP/1.4"
CRLF = b"\r\n"
HEADER_TERMINATOR = b"\r\n\r\n"
DEFAULT_TIMEOUT_SECONDS = 5.0
MAX_HEADER_BYTES = 64 * 1024
READ_CHUNK_SIZE = 4096
BODY_METHODS = {"SUBMIT", "REPLACE", "PATCH"}
ALLOWED_METHODS = {"FETCH", "INSPECT", "LIST", "SUBMIT", "REPLACE", "PATCH", "REMOVE", "PING"}
DEFAULT_BINARY_TYPE = "application/octet-stream"
DEFAULT_TEXT_TYPE = "text/plain; charset=utf-8"
PROBLEM_JSON_TYPE = "application/problem+json"
JSON_TYPE = "application/json"
AUTH_SCHEME = "Token"
DEFAULT_CACHE_MAX_AGE = 60
REQUEST_ID_HEADER = "X-Request-Id"
ACCEPT_RANGES_VALUE = "bytes"
METADATA_HEADER_PREFIX = "X-Meta-"
LIST_SORT_FIELDS = {"target", "last_modified", "size", "version", "content_type"}
STATUS_REASONS = {
    200: "OK",
    201: "CREATED",
    204: "NO CONTENT",
    206: "PARTIAL CONTENT",
    304: "NOT MODIFIED",
    400: "BAD REQUEST",
    401: "UNAUTHORIZED",
    404: "NOT FOUND",
    405: "METHOD NOT ALLOWED",
    406: "NOT ACCEPTABLE",
    411: "LENGTH REQUIRED",
    412: "PRECONDITION FAILED",
    416: "RANGE NOT SATISFIABLE",
    500: "INTERNAL SERVER ERROR",
}
